name: Deploy PWA Starter to GitHub Pages
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: generate_website
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13'

      - name: Install Dependencies
        run: npm install

      - name: Vite Build
        run: npm run build

      - name: Publish to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

